# Data Set Folders
data:
  data_set_folder: 'resources/data_sets/{data_set_code}/'
  data_set_combined: 'resources/data_sets_combined/{data_set_code}_comb.csv'

# Anomaly Detection: Models/Anomalies
ad:
  ad_model_file_path: 'resources/models/{ad_model_code}.h2o'
  ad_model_cache_file_path: 'resources/models/{ad_model_code}_training.h5'
  ad_model_cache_validation_file_path: 'resources/models/{ad_model_code}_validation.h5'
  anomalies_file_path: 'resources/anomalies/{ad_model_code}__{data_set_code}_{thr}.txt'
  anomalies_visualize_file_path: 'resources/anomalies_visualizations/{ad_model_code}__{data_set_code}_{thr}.png'

# OneClassSVM Failure Prediction: Models/Predictions
fp:
  predictions_file_path: 'resources/predictions/{ad_model_code}__{fp_train_data_set_code}_{novelties_set_thr}__prm_{nu}_{gamma}__{ad_model_code}__{experiment_data_set_code}_{anomalies_set_thr}.txt'
  fp_visualizations_file_path: 'resources/{output_folder}/{experiment_data_set_code}_{ad_model_code}_{fp_train_data_set_code}_{anomalies_set_thr}_{novelties_set_thr}_{nu}_{gamma}.png'
  localisations_file_path: 'resources/localisations/{oracle}_{rank_selection}/{ad_model_code}__{fp_train_data_set_code}_{novelties_set_thr}__prm_{nu}_{gamma}__{ad_model_code}__{experiment_data_set_code}_{anomalies_set_thr}.csv'
  localisations_stats_file_path: 'resources/localisations/stats/{oracle}_{rank_selection}___{ad_model_code}_{fp_train_data_set_code}_{novelties_set_thr}_{nu}_{gamma}_{anomalies_set_thr}.csv'

# Localizations
loc:
  loc_visualizations_file_dir: 'resources/localisations/loc_visualizations/{ad_model_code}_{fp_train_data_set_code}_{novelties_set_thr}_{nu}_{gamma}_{anomalies_set_thr}'
  loc_visualizations_file_name: '{oracle}_{experiment_data_set_code}_{rank_selection}.png'
  loc_visualizations_combined_file_name: '{oracle}_{experiment_data_set_code}.png'

# Logs
log:
  ad_train_log_file_path: 'resources/logs/ad_train_{ad_model_code}_log.txt'
  ad_detect_log_file_path: 'resources/logs/ad_detect_{ad_model_code}__{data_set_code}_{thr}_log.txt'
  fp_train_log_file_path: 'resources/logs/fp_train_{ad_model_code}__{fp_train_data_set_code}_{novelties_set_thr}__prm_{nu}_{gamma}_log.txt'
  fp_predict_log_file_path: 'resources/logs/fp_detect_{ad_model_code}__{fp_train_data_set_code}_{novelties_set_thr}__prm_{nu}_{gamma}__{ad_model_code}__{experiment_data_set_code}_{anomalies_set_thr}_log.txt'

  batch_ad_detect_log_file_path: 'resources/logs/batch_ad_detect_log.txt'
  batch_fp_train_log_file_path: 'resources/logs/batch_fp_train_log.txt'
  batch_fp_predict_log_file_path: 'resources/logs/batch_fp_predict_log.txt'
  batch_ad_detect_fp_train_fp_predict_log_file_path: 'resources/logs/batch_ad_detect_fp_train_fp_predict_log.txt'

  fp_visualize_log_file_path: 'resources/logs/fp_visualize.txt'
  fp_calc_stats_log_file_path: 'resources/logs/fp_calc_stats.txt'

  stats_combinatorial_search: 'resources/logs/stats_combinatorial_search.txt'

  level: 'debug'

# Nodes
nodes:
  pairs: 'redis-14 redis-3, redis-12 redis-1, redis-5 redis-16, redis-18 redis-7, redis-4 redis-15, redis-9 redis-20, redis-8 redis-19, redis-6 redis-17, redis-10 redis-11, redis-2 redis-13'

# H2O framework settings
h2o:
  local: true
  autoencoder:
    activation_function: "tanh"
    sparse: false
    l1: 10e-5
    max_w2: 10.0
    epochs: 400
    score_each_iteration: true
    reconstruction_error_threshold: 0.1

stats:
  stats_file_path: 'resources/stats/{experiment_data_set_code}_{ad_model_code}_{fp_train_data_set_code}_stats.txt'
  stats_file_path_ma: 'resources/stats_moving_average/{experiment_data_set_code}_{ad_model_code}_{fp_train_data_set_code}_stats_ma.txt'
  stats_best_file_path: 'resources/stats_best/{experiment_data_set_code}_{ad_model_code}_{fp_train_data_set_code}_stats_best.csv'
  stats_selected_file_path: 'resources/stats_best/stat_selected.csv'
  stats_selected_table_file_path: 'resources/stats_best/stat_selected.md'

  stats_by_params_combination_folder_path: 'resources/stats_by_combination/'
  stats_by_params_combination_file_path: 'resources/stats_by_combination/{number_of_good}_{anomalies_set_thr}_{novelties_set_thr}_{nu}_{gamma}.csv'